apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Parent-component
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-template: template:default/react-app1
    backstage.io/linguist: 'https://github.com/imprem/react-app1/tree/main'
  

spec:
  type: website
  lifecycle: unknown
  owner: guests
  
  consumesApis: 
    - weather-api
    - Tier1-token-api
    - product-api
  dependsOn:
    - component:ProductDetails_Component
    - component:Weather_Component
    - component:TokenBalance_Component