apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Weather_Component
  annotations:
    # github.com/project-slung: Sada-r/node-app
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-template: template:default/weather-app
    backstage.io/linguist: https://github.com/imprem/weather-app/tree/master
spec:
  type: service
  owner: guests
  lifecycle: experimental
  providesApis:
    - weather-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weather-api
  annotations:
    backstage.io/techdocs-ref: dir:.
  description: Get the weather details based on your city
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  definition:
    $text: https://github.com/imprem/weather-app/blob/master/weather-app-api-swagger.json    
